const tools = [
  {
    id: 0,
    name: "CSV Reader",
    desc: "View a summary of all your customers over the last month. ",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 1,
    name: "Pandas",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "free",
    enabled: true,
  },
  {
    id: 2,
    name: "PDF",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 3,
    name: "Excel Sheet",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 4,
    name: "Bing Search",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 5,
    name: "Summarizer",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 6,
    name: "MindsDb",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 7,
    name: "REPL",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 8,
    name: "JSON",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 9,
    name: "OPENAPI",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 10,
    name: "Google Search",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 11,
    name: "Wolfram Alpha",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 12,
    name: "Calculator",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 13,
    name: "IFTTT",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 14,
    name: "Weather",
    desc: "View a summary of all your customers over the last month.",
    status: "active",
    access: "premium",
    enabled: true,
  },
];

const datasources = [
  {
    id: 1,
    name: "Excel Sheet",
    status: "active",
    access: "premium",
    enabled: true,
  },
  {
    id: 2,
    name: "PDF File",
    status: "active",
    access: "premium",
    enabled: true,
  },
  { id: 3, name: "SQL", status: "active", access: "premium", enabled: true },
  {
    id: 4,
    name: "Google Drive",
    status: "active",
    access: "premium",
    enabled: true,
  },
  { id: 5, name: "Github", status: "active", access: "premium", enabled: true },
  { id: 9, name: "GitLab", status: "active", access: "premium", enabled: true },
];

const bots = [
  {
    id: 0,
    name: "Personal Assistant",
    description:
      "An bot that can interact with the outside world, have knowledge of your data.",
    link: "/",
    icon: "",
    enabled: true,
    datasources: [{ name: "documents" }],
    tools: [{ name: "Bing Search" }],
    access: "free",
  },
  {
    id: 1,
    name: "Learning Assistant",
    description: "A bot that help you learn and practice new skills.",
    link: "/",
    access: "premium",
    enabled: true,
    tools: [{ name: "Wolfram Alpha" }, { name: "Calculator" }],
    datasources: [{ name: "documents" }],
    icon: "",
  },
  {
    id: 6,
    name: "Teaching Assistant",
    description:
      "A bot that can create learning materials - quizzes for your class/course.",
    link: "/",
    access: "premium",
    enabled: true,
    tools: [
      { name: "Bing Search" },
      { name: "Wolfram Alpha" },
      { name: "Summarizer" },
    ],
    datasources: [{ name: "documents" }, { name: "Google Drive" }],
    icon: "",
  },
  {
    id: 2,
    name: "Financial Advisor",
    description: "A bot that can give you advises about your financials.",
    link: "/",
    icon: "",
    enabled: true,
    access: "premium",
    datasources: [{ name: "documents" }, { name: "Google Drive" }],
    tools: [{ name: "CSV Reader" }, { name: "Pandas" }, { name: "PDF" }],
  },
  {
    id: 2,
    name: "QA Assistant",
    description:
      "A bot that can answer questions about your personal documents.",
    link: "/",
    icon: "",
    enabled: true,
    access: "premium",
    datasources: [{ name: "documents" }, { name: "Google Drive" }],
    tools: [
      { name: "CSV Reader" },
      { name: "Pandas" },
      { name: "PDF" },
      { name: "Excel Sheet" },
      { name: "Bing Search" },
    ],
  },
  {
    id: 3,
    name: "Social Media Manager",
    description: "A bot that can manage your social media accounts.",
    icon: "",
    enabled: true,
    access: "premium",
    link: "/",
    tools: [{ name: "Bing Search" }, { name: "JSON" }, { name: "OPENAPI" }],
    datasources: [
      { name: "documents" },
      { name: "website" },
      { name: "Google Drive" },
    ],
  },
  {
    id: 4,
    name: "Ghost Writer",
    access: "premium",
    icon: "",
    enabled: true,
    description: "A bot that can write articles, books, and more.",
    link: "/",
    datasources: [
      { name: "documents" },
      { name: "website" },
      { name: "images" },
    ],
    tools: [{ name: "Bing Search" }, { name: "Summarizer" }],
  },
  {
    id: 7,
    name: "Data Analyst",
    access: "premium",
    icon: "",
    enabled: true,
    description: "A bot that can analyze your data and give you insights.",
    link: "/",
    datasources: [{ name: "documents" }, { name: "sql" }],
    tools: [
      { name: "CSV Reader" },
      { name: "Pandas" },
      { name: "PDF" },
      { name: "Excel Sheet" },
      { name: "Bing Search" },
      { name: "Summarizer" },
      { name: "MindsDb" },
    ],
  },
  {
    id: 5,
    name: "Code Assistant",
    description: "A bot that can help you write better code.",
    icon: "",
    access: "premium",
    enabled: true,
    link: "/",
    datasources: [{ name: "sql" }, { name: "gitlab" }, { name: "github" }],
    tools: [
      { name: "Bing Search" },
      { name: "JSON" },
      { name: "OPENAPI" },
      { name: "REPL" },
    ],
  },
];

export { tools, datasources, bots };
